# Welcome to Singularity Labs!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Singularity Labs's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Singularity Labs
email: labssingularity@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   Singularity Labs is a generative AI startup with focus on exploring trustworthy super-intelligent AI for a safer world
# baseurl: "" # the subpath of your site, e.g. /blog
baseurl: "/blog"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: labssingularity
discord_url: https://discord.gg/jc4xtF58Ve
github_username:  SingularityLabs-ai

# Build settings
theme: minima
# theme: jekyll-simple-dark
# theme: jekyll-text-theme
# remote_theme: jekyll/minima@3cdd14d
minima:
  logo: assets/logo.png
#   skin: dark

plugins:
  - jekyll-prettier
  - jekyll-feed
  - jekyll-dotenv
  - jekyll-postcss
  # - jekyll-paginate
# paginate: 5 # Posts per page for jekyll-simple-dark
# paginate_path: "page:num/"

# sass:
#   sass_dir: _sass

sass:
  load_paths:
    - _sass

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


permalink: /posts/:year/:month/:day/:title.html

postcss:
  cache: false

header_pages:
 - truthgpt.markdown
 - truthgptforgoogle.markdown
 - grandgpt.markdown
 - beyondbard.markdown
 - googlebard.markdown
 - googlegpt.markdown
 - scigpt.markdown
 - hindgpt.markdown
 - posts.markdown
 - about.markdown
 # - privacypolicy.markdown
